// ========================================================
// SUPABASE REALTIME WORKSPACE IMPLEMENTATION
// ========================================================

// 1. Inject your Supabase Workspace API Credentials here
const SUPABASE_URL = "https://flricibvmgkmtkptzwck.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZscmljaWJ2bWdrbXRrcHR6d2NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE2Mzg5NzIsImV4cCI6MjA5NzIxNDk3Mn0.XIBhapnKgGSE3m15Q5AJYN8lkekdfeFrlLbEGQ5ul-M";

// Initialize the global client layer
const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

let currentUser = null; 
let activeChatId = null;
let selectedChatObject = null; 
let messageSubscriptionChannel = null;
let activeSessionStartTime = new Date(); 

let audioMediaRecorder = null;
let recordedAudioChunks = [];
const trackedUnreadNotificationSet = new Set();

async function initDashboardPage() {
    if (!document.getElementById("users-container") && !document.getElementById("message-form")) {
        return; 
    }

    const savedUid = localStorage.getItem("session_uid");
    const savedName = localStorage.getItem("session_name");

    if (!savedUid) {
        window.location.href = "index.html";
        return; 
    }

    currentUser = { uid: savedUid, name: savedName, accountMode: "standard" };

    // Broadcast Online Presence Status via Postgres Update
    await supabase.from("users").update({ is_online: true }).eq("uid", currentUser.uid);

    // Keep UI Header names in sync dynamically via Realtime channel hooks
    supabase
        .channel(`public:users:uid=eq.${currentUser.uid}`)
        .on('postgres_changes', { event: 'UPDATE', schema: 'public', table: 'users', filter: `uid=eq.${currentUser.uid}` }, payload => {
            const data = payload.new;
            if(document.getElementById("current-user-title")) document.getElementById("current-user-title").innerText = data.name;
            if(document.getElementById("my-status-display")) document.getElementById("my-status-display").innerText = data.status || "Available";
        })
        .subscribe();

    populateUtilityUsersDropdown();

    // --- INSTANT GROUP CREATION ---
    const groupSelectMenu = document.getElementById("group-type-select");
    const groupPasswordField = document.getElementById("group-password-input");
    const createGroupActionBtn = document.getElementById("create-group-btn");

    if (groupSelectMenu && groupPasswordField) {
        groupSelectMenu.addEventListener("change", (e) => {
            if (e.target.value === "protected") {
                groupPasswordField.classList.remove("hidden");
            } else {
                groupPasswordField.classList.add("hidden");
            }
        });
    }

    if (createGroupActionBtn) {
        createGroupActionBtn.addEventListener("click", async () => {
            const groupNameInput = document.getElementById("group-name-input");
            const title = groupNameInput ? groupNameInput.value.trim() : "";
            const architectureType = groupSelectMenu ? groupSelectMenu.value : "public";
            const codeKeyPayload = groupPasswordField ? groupPasswordField.value.trim() : "";

            if (!title) {
                alert("Please declare an assignment name label for your room.");
                return;
            }

            try {
                const autoGeneratedRoomKey = "ROOM_" + Date.now();
                
                // Save Group configuration profile directly into unified profiles schema
                await supabase.from("users").insert([{
                    uid: autoGeneratedRoomKey,
                    name: `[ROOM] ${title}`,
                    status: `Open Global Channel (${architectureType.toUpperCase()})`,
                    is_group: true,
                    group_type: architectureType,
                    group_password: codeKeyPayload,
                    is_online: true
                }]);

                // Provisions Room Core Context Document
                await supabase.from("chats").insert([{
                    chat_id: autoGeneratedRoomKey,
                    participants: [currentUser.uid]
                }]);

                alert(`Global Chat Room "${title}" created successfully!`);
                if(groupNameInput) groupNameInput.value = "";
                if(groupPasswordField) groupPasswordField.value = "";
                executeTargetSearchQuery(""); 
            } catch (err) {
                alert("Room composition failure: " + err.message);
            }
        });
    }

    // --- UNREAD TRAFFIC ALERT PIPELINE VIA POSTGRES LOGICAL REPLICATION ---
    supabase
        .channel('public:messages')
        .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'messages' }, payload => {
            const packet = payload.new;
            if (packet.sender_id !== currentUser.uid && packet.chat_id !== activeChatId) {
                trackedUnreadNotificationSet.add(packet.chat_id);
                renderSidebarUnreadAlertBadge(packet.chat_id);
            }
        })
        .subscribe();

    // --- VOICE MEMO CAPTURE MECHANIC VIA SUPABASE STORAGE BUCKETS ---
    const recordVoiceBtn = document.getElementById("voice-record-btn");
    const recordStatusText = document.getElementById("voice-recording-status");

    if (recordVoiceBtn) {
        recordVoiceBtn.addEventListener("click", async () => {
            if (!activeChatId) return;
            if (!audioMediaRecorder) {
                try {
                    const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
                    audioMediaRecorder = new MediaRecorder(stream);
                    audioMediaRecorder.ondataavailable = (e) => { if (e.data.size > 0) recordedAudioChunks.push(e.data); };
                    audioMediaRecorder.onstop = async () => {
                        const audioBlob = new Blob(recordedAudioChunks, { type: "audio/ogg; codecs=opus" });
                        recordedAudioChunks = [];
                        if(recordStatusText) recordStatusText.classList.add("hidden");
                        recordVoiceBtn.style.color = "initial";

                        const filePath = `voice_memos/${activeChatId}/${Date.now()}_clip.ogg`;
                        
                        // Upload to Supabase Storage Bucket ('chat-media')
                        const { data, error } = await supabase.storage.from('chat-media').upload(filePath, audioBlob);
                        if (error) throw error;

                        const { data: urlData } = supabase.storage.from('chat-media').getPublicUrl(filePath);

                        await supabase.from("messages").insert([{
                            chat_id: activeChatId,
                            text: "Voice Note Transmission",
                            file_url: urlData.publicUrl,
                            type: "audio",
                            sender_id: currentUser.uid,
                            sender_name: currentUser.name
                        }]);
                    };
                } catch (err) {
                    alert("Audio device access denied: " + err.message);
                    return;
                }
            }

            if (audioMediaRecorder.state === "inactive") {
                audioMediaRecorder.start();
                if(recordStatusText) recordStatusText.classList.remove("hidden");
                recordVoiceBtn.style.color = "#ea0038";
            } else {
                audioMediaRecorder.stop();
            }
        });
    }

    const searchField = document.getElementById("search-users");
    if (searchField) {
        searchField.addEventListener("input", (e) => executeTargetSearchQuery(e.target.value.trim()));
    }
    executeTargetSearchQuery(""); 

    const messageForm = document.getElementById("message-form");
    if (messageForm) {
        messageForm.addEventListener("submit", async (e) => {
            e.preventDefault();
            const input = document.getElementById("message-input");
            if (!input || !input.value.trim() || !activeChatId) return;

            const text = input.value.trim();
            input.value = "";

            await supabase.from("messages").insert([{
                chat_id: activeChatId,
                text: text,
                type: "text",
                sender_id: currentUser.uid,
                sender_name: currentUser.name
            }]);
        });
    }

    const logoutBtn = document.getElementById("logout-btn");
    if (logoutBtn) {
        logoutBtn.addEventListener("click", async () => {
            await supabase.from("users").update({ is_online: false }).eq("uid", currentUser.uid);
            localStorage.clear();
            await supabase.auth.signOut();
            window.location.href = "index.html";
        });
    }
}

async function populateUtilityUsersDropdown() {
    const dropdownMenu = document.getElementById("utility-member-dropdown");
    if (!dropdownMenu) return;
    
    const { data: workspaceUsers } = await supabase.from("users").select("*").eq("is_group", false);
    dropdownMenu.innerHTML = `<option value="">-- Choose Workspace Profile --</option>`;
    
    workspaceUsers.forEach((user) => {
        if (user.uid !== currentUser.uid) {
            const opt = document.createElement("option");
            opt.value = user.uid;
            opt.innerText = user.name;
            dropdownMenu.appendChild(opt);
        }
    });
}

async function executeTargetSearchQuery(keyword) {
    const listCanvas = document.getElementById("users-container");
    if (!listCanvas) return;
    listCanvas.innerHTML = "";

    let queryBuilder = supabase.from("users").select("*");
    
    if (keyword) {
        queryBuilder = queryBuilder.ilike("name", `%${keyword}%`);
    }

    const { data: usersList } = await queryBuilder;
    if (!usersList) return;

    // Split and sequence view array layout cleanly (Groups on top, private channels under)
    usersList.forEach(item => { if(item.is_group) buildSidebarChannelRowElement(item); });
    usersList.forEach(item => { if(!item.is_group && item.uid !== currentUser.uid) buildSidebarChannelRowElement(item); });
}

function buildSidebarChannelRowElement(userData) {
    const canvas = document.getElementById("users-container");
    let rowElement = document.createElement("div");
    canvas.appendChild(rowElement);
    
    rowElement.style = "display:flex; align-items:center; justify-content:space-between; padding:12px 16px; cursor:pointer; border-bottom:1px solid #f8f9fa;";

    const isRoomChannel = userData.is_group === true;
    let badgeClass = userData.is_online ? "status-online" : "status-offline";
    let statusTextLabel = userData.is_online ? "online" : "offline";

    if (isRoomChannel) {
        badgeClass = (userData.group_type === "protected") ? "status-protected" : "status-public";
        statusTextLabel = (userData.group_type === "protected") ? "🔒 Protected" : "🌐 Public";
    }

    rowElement.innerHTML = `
        <div style="display:flex; align-items:center; gap:12px; flex:1; min-width:0;">
            <div style="background:${isRoomChannel ? '#008069' : '#00a884'}; color:white; width:44px; height:44px; border-radius:50%; display:flex; align-items:center; justify-content:center; font-weight:bold; font-size:18px;">
                ${isRoomChannel ? '👥' : userData.name.charAt(0).toUpperCase()}
            </div>
            <div style="flex:1; min-width:0;">
                <h4 style="margin:0; font-size:14px; color:#111b21; font-weight:600;">
                    ${userData.name} <span class="status-badge ${badgeClass}">${statusTextLabel}</span>
                </h4>
                <p style="margin:2px 0 0 0; font-size:12px; color:#667781;">${userData.status || 'Available'}</p>
            </div>
        </div>
        <div id="badge-holder-${userData.uid}"></div>
    `;

    rowElement.addEventListener("click", async () => {
        if (isRoomChannel && userData.group_type === "protected") {
            const clientAttemptToken = prompt(`Security Verification required.\nEnter password to access "${userData.name}":`);
            if (clientAttemptToken !== userData.group_password) {
                alert("Authorization Denied: Invalid password key.");
                return;
            }
        }

        activeChatId = userData.uid;
        selectedChatObject = userData; 
        activeSessionStartTime = new Date();

        document.getElementById("no-chat-selected").classList.add("hidden");
        document.getElementById("active-chat-area").classList.remove("hidden");
        document.getElementById("chat-header-name").innerText = userData.name;

        // Upsert standard core chat structure references
        await supabase.from("chats").upsert([{ chat_id: activeChatId, participants: [currentUser.uid] }]);

        bindLiveIsolatedMessageStreams(activeChatId);
    });
}

function bindLiveIsolatedMessageStreams(chatId) {
    if (messageSubscriptionChannel) {
        supabase.removeChannel(messageSubscriptionChannel);
    }

    // Retrieve historical chat record buffer via standard SELECT
    supabase.from("messages").select("*").eq("chat_id", chatId).order("created_at", { ascending: true })
        .then(({ data }) => {
            const chatBoxWindow = document.getElementById("message-stream");
            chatBoxWindow.innerHTML = "";
            if(data) data.forEach(msg => renderSingleMessageBubble(msg));
        });

    // Establish live listener over Postgres mutations inside selected room stream
    messageSubscriptionChannel = supabase
        .channel(`room:${chatId}`)
        .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'messages', filter: `chat_id=eq.${chatId}` }, payload => {
            renderSingleMessageBubble(payload.new);
        })
        .subscribe();
}

function renderSingleMessageBubble(data) {
    const chatBoxWindow = document.getElementById("message-stream");
    const bubbleRow = document.createElement("div");
    const isMe = data.sender_id === currentUser.uid;
    
    bubbleRow.style = `display:flex; justify-content:${isMe ? 'flex-end' : 'flex-start'}; margin-bottom:12px;`;
    
    let visualPayloadOutputBlock = "";
    if (data.type === "audio") {
        visualPayloadOutputBlock = `<audio src="${data.file_url}" controls style="max-width:250px;"></audio>`;
    } else {
        visualPayloadOutputBlock = `
            <div style="display:flex; justify-content:between; font-size:11px; margin-bottom:3px;">
                <span style="font-weight:bold; color:#008069;">${data.sender_name}</span>
            </div>
            <p style="margin:0; font-size:14px; color:#111b21;">${data.text}</p>
        `;
    }

    bubbleRow.innerHTML = `<div style="background:${isMe ? '#d9fdd3' : '#ffffff'}; padding:9px 14px; border-radius:10px; max-width:68%;">${visualPayloadOutputBlock}</div>`;
    chatBoxWindow.appendChild(bubbleRow);
    chatBoxWindow.scrollTop = chatBoxWindow.scrollHeight;
}

document.addEventListener("DOMContentLoaded", initDashboardPage);
